### PR TITLE
mention that midje is supported as well

### PR DESCRIPTION
**Pull request by orend**

### CODE REVIEW

**Comment by jstrength** [comment]
It doesn't seem to integrate fully with midje.
When you have facts wrapped in deftest the  'Ran x tests containing y assertions.' message works.
Without the wrapping, you still get the coverage reported correctly, but this message doesn't work.

**Comment by palfrey** [comment]
I'm not going to merge this until there's an example for midje working correctly. I may get around to doing so eventually, but if someone else has the time to do so that would speed things up a lot!

**Comment by palfrey** [comment]
Reason why the 'Ran x tests containing y assertions.' message doesn't work by default is that Cloverage uses `clojure.test/run-tests` internally and needs it's results in order to be able to do the right thing. As midje doesn't return the right results for "lein test", it also fails here.

Worse, `midje.repl/load-tests` doesn't actually return test results. The only way we'd be able to get proper midje support is doing something like https://github.com/glittershark/midje-notifier/blob/master/src/midje/notifier.clj and using the data from the notifier to give us the test result data. https://github.com/glittershark/midje-notifier/blob/master/src/midje/notifier.clj.

**Comment by palfrey** [comment]
Given the current documentation is fine as is at the moment, I've added a new ticket for actual midje support (#64) and I'm closing this.

**Pull request closed without merging**
