### PR TITLE
More cherry-picks from @rfkm's fork

### PR DESCRIPTION
**Pull request by rm-hull**

### CODE REVIEW

**Comment by lvh** [comment]
Looks like there's a conflict that needs resolving now.

**Comment by rm-hull** [comment]
merge conflict should be zapped now, was due to deleted file that got changed in the _Fix outdated `project.clj`_ commit

**Comment by rm-hull** [comment]
Quite like these release / deploy changes on @rfkm's fork: f303429, cbdbe14, 174c3c2, 5965c8a but think they should probably be a separate PR (and it's also predicated on being able to actually cut a release...)

**Comment by rfkm** [comment]
@rm-hull 
Wow, thank you for your hard work! (and sorry for my lack of activity :( )

BTW, indentations look weird. There are many hard-tabs in the changes though my original commits  (and even the original code) don't contain them. You might want to reformat them.

**Comment by lvh** [comment]
Huh; didn't notice those in review. Perhaps we should have an editorconfig file and eclint.

**Comment by rm-hull** [comment]
Ah, I used p4merge to fix up the conflicts, maybe that added them.
Normally I use vim and expand tabs.

**Comment by lvh** [comment]
LGTM!

**Pull request merged**
