### PR TITLE
Correct wrapping of Records

### PR DESCRIPTION
**Pull request by palfrey**
This corrects the issue raised in #66, but at the cost of not doing full instrumentation for Records, which we'll have to address at a future date.

### CODE REVIEW

**Comment by palfrey** [comment]
So, it actually turns out that we weren't doing *enough* wrapping of Records...

**Comment by palfrey** [comment]
If anyone has any larger code bases they want to check this against before I merge this, that would be most welcomed.

Test steps:
1. Checkout this branch.
2. Go into cloverage folder, and run lein install to install a local snapshot copy of Cloverage.
3. Run CLOVERAGE_VERSION=1.0.6-SNAPSHOT lein cloverage against your larger code base

**Comment by MichaelBlume** [comment]
Yep, works for me =)

**Comment by BinarySplit** [comment]
Works on my code base too :D

**Comment by palfrey** [comment]
Thanks for all your responses, that's been very helpful

**Pull request merged**
