### PR TITLE
Added support for building on CircleCi

### PR DESCRIPTION
**Pull request by drazisil**

### CODE REVIEW

**Comment by lvh** [comment]
Thanks for your contribution! Could you help me understand the benefit of running CI in two places?

**Comment by drazisil** [comment]
There is none, but as CircleCi is a CI/CD platform written 100% in Clojure I felt it was a good fit :)

Plus I feel it's a nicer interface.

(Disclosure, I work at CircleCi, but I'm suggesting this as a personal user myself, I'd love for you give it a try and tell me what you think)

**Comment by lvh** [comment]
Okiedokie :) This only includes the config; I imagine a badge would also be in order. I'm also assuming we're keeping both pieces of CI indefinitely, since this isn't a full replacement. At some point, we should then probably also move the CI scripts out of travis.yml/circle.yml so that both run identical tooling... Thoughts? (Not saying that should be for this PR.)

**Comment by drazisil** [comment]
I added the badge, but it will be broken until you build on CircleCi. Regarding the comment of "not a full replacement" what is missing?

**Comment by rm-hull** [comment]
> Regarding the comment of "not a full replacement" what is missing?

I think the travis script runs a `deploy.sh` script which does a snapshot (and possibly not-snapshot) release to clojars when master is updated.

**Comment by drazisil** [comment]
Ah yes. I didn't add that to mine because I don't have the credentials, but CircleCi does support it :)

**Comment by lvh** [comment]
Sorry; I should've been more clear about that part. The problem there is lack of access to credentials, not anything with CircleCI.

**Pull request merged**
