### PR TITLE
Coveralls report: record num hits & source digest

### PR DESCRIPTION
**Pull request by rm-hull**
Looking at stats in coveralls, the number of times a line was executed was either 0, 1 or 2 when I knew there should be higher numbers. Seems like the original implementation used a code of 0 for no coverage, 1 for partial (conditional) coverage, 2 for full coverage (was this before cloverage supported the `:hit` line attribute?)

Also according to https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction,
the source files contains a `source_digest` and not the entire file
contents.

With this fix, a typical (formatted) _coveralls.json_ file would look like:

```json
{  
   "service_job_id":null,
   "service_name":null,
   "source_files":[  
      {  
         "name":"wam/parser.clj",
         "source_digest":"49c327abfa13cc5ffddb85e1659881f2",
         "coverage":[  
            null,
            null,
            null,
            null,
            null,
            null,

"--- 8< --- snipped --- 8< ---",

            4,
            3,
            12,
            null,
            1,
            3,
            null,
            1,
            2,
            null,
            4,
            9,
            null,
            null,
            1,
            6,
            null,
            1,
            1,
            2,
            null,
            4,
            7,
            null,
            1,
            82,
            6,
            5,
            6,
            3,
            null,
            1,
            null,
            null,
            0,
            null,
            null,
            0,
            null,
            1,
            null,
            null,
            1,
            14,
            null,
            5,
            1,
            null,
            1,
            null,
            4,
            null,
            3,
            null,
            1,
            4,
            null,
            4,
            null,
            3
         ]
      }
   ]
}
```

Dont know whether coveralls API has evolved since the report was added

UPDATE: referenced https://github.com/lemurheavy/coveralls-public/issues/216

### CODE REVIEW

**Comment by lvh** [comment]
@rm-hull This LGTM. Did you get a chance to send this to Cloverage? It looks like it'd have the intended effect, but something about the proof of the pudding :)

**Comment by rm-hull** [comment]
Here is a coverage report from the 'vanilla' cloverage: https://coveralls.io/builds/7339496/source?filename=clustering%2Fcore%2Fk_means.clj

Here is another coverage report with the patched cloverage code for the same file (no changes to the source): https://coveralls.io/builds/7359011/source?filename=clustering%2Fcore%2Fk_means.clj

the 'before' build shows x2's everywhere, whereas the after shows line hits consistent with what I'd've expected.

**Comment by lvh** [comment]
LGTM! Would you mind adding a note to the README's changelog?

**Comment by JacekLach** [comment]
Using the number as a status rather than hit count could have been a poor's man attempt at tracking partial coverage in coveralls. I don't think they support it in any other way, unfortunately.

This way is more intuitive, I guess, and if you think coverall's more useful for the statistics rather than the file view, it might be an improvement. I'm somewhat concerned about losing all information about partial coverage (perhaps better to mark partial lines as not covered instead?).

**Comment by lvh** [comment]
@rm-hull This needs to have conflicts resolved. I'll handle the changelog part if you'd like.
@JacekLach I'm not sure I understand, I thought coveralls.io doesn't support partial coverage _at all_?

**Comment by rm-hull** [comment]
Conflicts fixed.

For me, using the line hit-count as a coded-value for none/partial/full branch coverage seems like a fudge, and likely to cause future confusion for others (as it did for me). 

Possibly the best thing to do is nudge the coveralls maintainers to see how feasible it is to implement branch coverage properly (related issues, as far as i can see nothing happening though: https://github.com/lemurheavy/coveralls-public/issues/31 and https://github.com/lemurheavy/coveralls-public/issues/216)

**Comment by lvh** [comment]
Hm, yeah, I agree with @rm-hull; I've conferred with some people who have been working on @pyca projects for years and this isn't exactly a new issue...

**Pull request merged**
